export const SICKNESS_TITLES = [
  "🤒 Diagnosed with {illness}",
  "🚨 Health Alert: {illness}",
  "🦠 You Caught {illness}!",
  "⚠️ Medical Update: {illness}",
  "🩺 Diagnosis: {illness}",
  "🤢 Feeling Terribly Ill: {illness}",
  "🤒 Stricken by {illness}",
  "🚨 Urgent: {illness} Detected",
  "🦠 Uh oh... {illness}",
  "⚠️ Bad News: {illness}",
  "🩺 Doctor's Note: {illness}",
  "🤒 You've Come Down With {illness}",
  "🚨 Emergency: {illness}",
  "🦠 Infected with {illness}",
  "⚠️ Caution: {illness}",
  "🩺 Test Results: {illness}",
  "🤒 Sick in Bed: {illness}",
  "🚨 Health Crisis: {illness}",
  "🦠 A Wild {illness} Appeared!",
  "⚠️ It's Official: {illness}",
  "🩺 Confirmed Case of {illness}",
  "🤒 Suffering from {illness}",
  "🚨 Warning: {illness} Symptoms",
  "🦠 Unlucky! You got {illness}",
  "⚠️ Body Failing: {illness}",
  "🩺 Medical Record Updated: {illness}",
  "🤒 Down for the Count: {illness}",
  "🚨 Severe Discomfort: {illness}",
  "🦠 Bugs Got You: {illness}",
  "⚠️ Health Compromised: {illness}"
];

export const SICKNESS_DESCRIPTIONS = [
  "You have suddenly fallen ill with {illness} ({type} condition). What do you want to do about it?",
  "You woke up feeling terrible. The diagnosis is {illness} ({type} condition). How will you handle this?",
  "It's official, you have contracted {illness} ({type} condition). It's time to make a decision on your health.",
  "Your body is aching and a quick check confirms {illness} ({type} condition). What's the plan?",
  "You've been diagnosed with {illness} ({type} condition). You feel miserable. What is your next move?",
  "Out of nowhere, {illness} ({type} condition) has struck you down. How will you respond?",
  "A sudden wave of nausea and fatigue hits you. It's {illness} ({type} condition). What now?",
  "You're bedridden with {illness} ({type} condition). Every joint hurts. What should you do?",
  "The doctor's tests came back positive for {illness} ({type} condition). Time to choose a treatment.",
  "You are suffering through the early stages of {illness} ({type} condition). How will you fight it?",
  "Your immune system failed you, leading to {illness} ({type} condition). What is your strategy?",
  "You've unfortunately caught {illness} ({type} condition). The symptoms are unbearable. Next steps?",
  "It seems you couldn't escape the season without catching {illness} ({type} condition). Action plan?",
  "You are currently battling {illness} ({type} condition). How do you plan to recover?",
  "A severe case of {illness} ({type} condition) has left you completely drained. What will you do?",
  "You've been struck by {illness} ({type} condition), ruining your plans for the week. What's your response?",
  "Medical tests confirm {illness} ({type} condition). You need to take care of this. How?",
  "You are exhibiting all the classic symptoms of {illness} ({type} condition). Choose your treatment.",
  "Your health has taken a sharp dive due to {illness} ({type} condition). What is your course of action?",
  "You've developed {illness} ({type} condition). Your body feels like lead. What now?",
  "An unexpected bout of {illness} ({type} condition) has knocked you off your feet. How will you cope?",
  "You are officially a victim of {illness} ({type} condition). What is your preferred method of healing?",
  "Your throat is sore and your head is pounding. It's {illness} ({type} condition). What do you do?",
  "You've been diagnosed with {illness} ({type} condition), and it's taking a toll on your body. Next move?",
  "A sudden onset of {illness} ({type} condition) has you questioning your life choices. How to recover?",
  "You're feeling absolutely awful thanks to {illness} ({type} condition). What's the remedy?",
  "The diagnosis is in: {illness} ({type} condition). You need to act fast. What's the plan?",
  "You've been hit hard by {illness} ({type} condition). The pain is real. How will you handle it?",
  "Your worst fears are confirmed. You have {illness} ({type} condition). What will you do next?",
  "You are grappling with {illness} ({type} condition). It's time to make a tough decision regarding your health."
];

export const IGNORE_TEXTS = [
  "Fuck it, don't care. Let my immune system handle it.",
  "Ignore it completely. I have better things to do.",
  "Tough it out. Pain is weakness leaving the body.",
  "Walk it off. It's probably nothing serious.",
  "Pretend it doesn't exist and go about my day.",
  "Refuse to acknowledge it. Mind over matter.",
  "Just push through the pain. I ain't got time to bleed.",
  "I'm too busy to be sick. Ignore the symptoms.",
  "It will pass. I'll just grind through it.",
  "Denial is the best medicine. I'm totally fine.",
  "Suck it up and stop complaining.",
  "I'll just ignore it until it magically disappears.",
  "Acknowledge it, then violently repress it.",
  "I don't have time for this. Keep working.",
  "Whatever, it's just a flesh wound.",
  "I'll just pretend I'm healthy. Fake it till you make it.",
  "No time for sickness, only the grind.",
  "Let my body figure it out on its own.",
  "I'll just ignore the agony and hope for the best.",
  "I refuse to be a victim of my own biology.",
  "Just ignore the fever and keep moving.",
  "Complaining won't fix it, so I'll just do nothing.",
  "I'm sure it's just allergies. Ignore.",
  "I'll sleep it off... eventually. For now, ignore.",
  "Sickness is a mindset. I choose not to be sick.",
  "I'll just out-stubborn the disease.",
  "I don't believe in germs. Carry on.",
  "I'll just ignore it and let fate decide.",
  "Only the weak go to the doctor. I'll tough it out.",
  "I'm built different. I'll just ignore it."
];

export const PRAY_TEXTS = [
  "Pray to the heavens for a speedy recovery.",
  "Light a candle and pray for health.",
  "Meditate and send positive healing vibes.",
  "Ask the universe to spare you from this agony.",
  "Chant a healing mantra and hope for the best.",
  "Pray to whatever deity will listen.",
  "Burn some sage and pray for spiritual healing.",
  "Send thoughts and prayers to yourself.",
  "Beg the cosmos for a miraculous recovery.",
  "Engage in deep prayer and ask for strength.",
  "Look to the sky and pray for relief.",
  "Consult the stars and pray for a better tomorrow.",
  "Pray fervently that this isn't the end.",
  "Offer a silent prayer to the health gods.",
  "Focus your chi and pray for wellness.",
  "Seek divine intervention for your sickness.",
  "Pray that this is just a bad dream.",
  "Drop to your knees and pray for a cure.",
  "Send out positive energy and pray it returns as health.",
  "Pray to the ancestors for their healing wisdom.",
  "Clasp your hands and pray for mercy.",
  "Pray that your immune system gets a divine buff.",
  "Whisper a prayer into the wind.",
  "Hold a healing crystal and pray.",
  "Pray for the strength to endure this.",
  "Seek inner peace and pray for outer health.",
  "Pray that you wake up feeling 100% better.",
  "Offer a solemn prayer for your ailing body.",
  "Pray that the universe takes pity on you.",
  "Just close your eyes and pray it goes away."
];

export const WATER_TEXTS = [
  "Just drink lots of water and rest.",
  "Stay in bed, drink tea, and rest up.",
  "Hydrate and sleep it off.",
  "Chug a gallon of water and take a nap.",
  "Drink some orange juice and get plenty of sleep.",
  "Consume fluids and rest for 24 hours.",
  "Drink herbal tea and stay under the covers.",
  "Hydrate aggressively and hope for the best.",
  "Drink chicken soup, water, and sleep.",
  "Stay hydrated and avoid strenuous activity.",
  "Drink warm water with lemon and go to bed.",
  "Just focus on hydration and deep sleep.",
  "Drink electrolytes and take a long rest.",
  "Sip water constantly and stay in bed.",
  "Drink hot broth and get some much-needed rest.",
  "Hydrate, hydrate, hydrate. And sleep.",
  "Drink a ton of water and hibernate.",
  "Stick to a strict regimen of water and naps.",
  "Drink ginger tea and rest your body.",
  "Hydrate like your life depends on it and sleep.",
  "Drink lots of fluids and take it easy.",
  "Stay in bed with a massive jug of water.",
  "Drink soothing tea and rest your eyes.",
  "Prioritize hydration and a solid 8 hours of sleep.",
  "Drink water until you can't anymore, then rest.",
  "Consume clear liquids and stay horizontal.",
  "Drink warm fluids and get plenty of rest.",
  "Hydrate thoroughly and give your body a break.",
  "Drink coconut water and take a long nap.",
  "Just stick to water and rest, the classic cure."
];
